BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path=public,extensions;
SELECT no_plan();
\ir ../fixtures/social_history.inc
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',(SELECT a::text FROM social_fixture),true);
CREATE TEMP TABLE revoked_page AS SELECT public.list_social_shared_games((SELECT b FROM social_fixture),NULL,1) AS page;
RESET ROLE;
DELETE FROM public.friendships WHERE requester_account_id=(SELECT a FROM social_fixture) AND addressee_account_id=(SELECT b FROM social_fixture);
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.list_social_shared_games((SELECT b FROM social_fixture),(SELECT page->>'next_cursor' FROM revoked_page),1)$$,'P0001','comparison_not_allowed','revocation between pages denies cursor replay');
SELECT throws_ok($$SELECT public.list_social_shared_timeline((SELECT b FROM social_fixture))$$,'P0001','comparison_not_allowed','timeline reauthorizes');
SELECT is((SELECT count(*)::integer FROM public.completed_session_summaries),4,'personal participation remains after unfriend');
RESET ROLE;
INSERT INTO private.account_blocks(blocker_account_id,blocked_account_id) SELECT a,b FROM social_fixture;
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.get_social_history((SELECT b FROM social_fixture))$$,'P0001','comparison_not_allowed','own block rejects read');
RESET ROLE;
DELETE FROM private.account_blocks WHERE blocker_account_id=(SELECT a FROM social_fixture);
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.get_social_history((SELECT b FROM social_fixture))$$,'P0001','comparison_not_allowed','unblock does not restore friendship');
SELECT set_config('request.jwt.claim.sub','28000000-0000-4000-8000-999999999999',true);
SELECT throws_ok($$SELECT public.get_social_history((SELECT b FROM social_fixture))$$,'P0001','username_required','deleted actor with stale JWT denied');
SELECT set_config('request.jwt.claim.sub','',true);
SELECT throws_ok($$SELECT public.get_social_history((SELECT b FROM social_fixture))$$,'P0001','authentication_required','expired authentication denied');
RESET ROLE;
SELECT ok(NOT has_function_privilege('authenticated','private.social_history_page(uuid,text,integer,boolean)','EXECUTE'),'internal arbitrary projector has no direct grant');
SELECT ok(NOT has_function_privilege('anon','private.get_social_history(uuid,integer)','EXECUTE'),'anon private call denied');
SELECT * FROM finish();
ROLLBACK;
